### ISSUE TITLE
app_rpt - DNS lookup should check for stale records

### ISSUE THREAD

**Issue by KB4MDD** [AllStarLink/app_rpt#141]
The DNS node lookup, implemented with issue #93, needs to check for stale DNS records.  The DNS server may not purge the records in a timely manner.  Records older than 30 minutes should be discarded.

**Comment by Allan-N** [comment]
I think we've got the DNS infrastructure issues all settled now.  To @jxmx to confirm.

**Comment by jxmx** [comment]
The DNS infrastructure appears to be working fine. This can be closed.
