### ISSUE TITLE
Murdoch Coredump 2023-04-27

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/app_rpt#159]
Attached full.txt and a grep of the asterisk log for that day.

[core-asterisk-2023-04-27T15-34-54Z-full.txt](https://github.com/InterLinked1/app_rpt/files/11362309/core-asterisk-2023-04-27T15-34-54Z-full.txt)
[log_2023-04-27.txt](https://github.com/InterLinked1/app_rpt/files/11362322/log_2023-04-27.txt)

**Comment by jxmx** [comment]
Seems to be obsolete. Please re-open if there is a fixable problem here.
