### ISSUE TITLE
Tri-State Cored after 0ver 40 days uptime

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/app_rpt#174]
Tri-State runs only the DAHDI/pseudo channel driver. Of course there have been no updates to this server in the uptime. But it will be interesting to see what caused the crash. Maybe it's something that has already been fixed.

[core-asterisk-2023-06-08T23-12-59Z-full.txt](https://github.com/InterLinked1/app_rpt/files/11698673/core-asterisk-2023-06-08T23-12-59Z-full.txt)

**Comment by jxmx** [comment]
Seems to be obsolete. Please re-open if there is a fixable problem here.
