### ISSUE TITLE
SCRN Not passing Audio

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/app_rpt#179]
Users called me reporting audio is not passing between sites (chan_voter connected). Did not find a core file. Sorry log is so big, I'm in a time crunch had to upload the whole log. 

Look above second "Asterisk 20" to see problems. I noticed lots of JB re-sync but did have a chance to look in detail. 

[Messages_20230617.log](https://github.com/InterLinked1/app_rpt/files/11779901/Messages_20230617.log)

**Comment by jxmx** [comment]
Seems to be obsolete. Please re-open if there is a fixable problem here.
