### ISSUE TITLE
app_rpt: ast_frame_free memory corruption in rpt()

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/app_rpt#206]
Can't find anything related in the logs.

[core-asterisk-2023-08-05T06-20-05Z-full.txt](https://github.com/InterLinked1/app_rpt/files/12293266/core-asterisk-2023-08-05T06-20-05Z-full.txt)

**Comment by jxmx** [comment]
Seems to be obsolete. Please re-open if there is a fixable problem here.
