### ISSUE TITLE
SimpleUSB CPU Utilization w/o Configured Device

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/app_rpt#330]
On my Rpi5 with a configured SimpleUSB device unplugged one CPU and one thread reach near 100%. No impact to node performance is noticed. CPU utilization returns to normal when device is plugged in. 

<img width="1336" alt="Screenshot 2024-05-16 at 10 43 54 AM" src="https://github.com/AllStarLink/app_rpt/assets/1526362/cf52a2b8-72a3-4ac7-8adc-16c0f347ef55">

**Comment by jxmx** [comment]
Seems to be obsolete. Please re-open if there is a fixable problem here.
