### ISSUE TITLE
Pulls for Post-Pull Review by Naveen

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/app_rpt#349]
Per Tim, these pulls need to be reviewed that others made to fix release-week issues.

- [x] https://github.com/AllStarLink/app_rpt/pull/348
- [x] https://github.com/AllStarLink/app_rpt/pull/346
- [x] https://github.com/AllStarLink/app_rpt/pull/343
- [x] https://github.com/AllStarLink/app_rpt/pull/342
- [x] https://github.com/AllStarLink/app_rpt/pull/340
- [x] https://github.com/AllStarLink/app_rpt/pull/337

**Comment by tsawyer** [comment]
For now these go to the devel package stream for in-house testing and no further.

**Comment by tsawyer** [comment]
Naveen gave us the go ahead with one suggestion on #346.
