### ISSUE TITLE
Pulls for Post-Pull Review by Naveen

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/app_rpt#376]
Others have made pull requests to correct reported issues.  Per Tim, these pulls need to be reviewed.

- [x] https://github.com/AllStarLink/app_rpt/pull/363
- [x] https://github.com/AllStarLink/app_rpt/pull/366
- [x] https://github.com/AllStarLink/app_rpt/pull/372
- [x] https://github.com/AllStarLink/app_rpt/pull/373

If OK, please check each pull request.  If changes are requested/needed, please file a new issue.

**Comment by InterLinked1** [comment]
> Others have made pull requests to correct reported issues. Per Tim, these pulls need to be reviewed.
> 
> * [x]  [app_rpt: Correct issues with the autopatch #363](https://github.com/AllStarLink/app_rpt/pull/363)
> * [x]  [Remove tail when beaconing #366](https://github.com/AllStarLink/app_rpt/pull/366)
> * [x]  [app_rpt: Correct 5 digit node lookup from 4 digit node #372](https://github.com/AllStarLink/app_rpt/pull/372)
> * [x]  [Increase HTTP registration timeout #373](https://github.com/AllStarLink/app_rpt/pull/373)
> 
> If OK, please check each pull request. If changes are requested/needed, please file a new issue.

Sorry for the delay here.

363 and 373 look completely good.
366 didn't follow commit/coding guidelines, but there is no point making another change just to address that. Somebody can get that when going through and addressing that issue en masse later.
372 it might be nice to have a warning if the original config setting was invalid, but not too sure what the context is there.
