### ISSUE TITLE
app_rpt: AMI output consistency issues with rpt_manager.c

### ISSUE THREAD

**Issue by W6HBR** [AllStarLink/app_rpt#395]
I've been doing data captures from the AMI and found a couple of inconsistencies with a couple of the data items being reported.

First is for RPT_RXKEYED - there are two extra CRLF's added which cause the last line of the reported data to be orphaned into its own message as well as adding an extra unnecessary end-of-message terminator.  AMI messages are terminated with a double CRLF (\r\n\r\n).  In this case, the LastTxKeyedTime has an extra CRLF before and after the reported line. (see image)
![image](https://github.com/user-attachments/assets/cd082286-828c-4efa-ab30-9948c47120d2)

Not sure where the extra CRLF's in RPT_RXKEYED are coming from as the rpt_manager_trigger function appears correct.  Possibly the date/time value being passed already has a CRLF at the end causing this.
![image](https://github.com/user-attachments/assets/6cf1244b-e2b6-483a-a8c3-372b19cb4f2b)
 
 
The second issue is purely cosmetic, but also adds an extra unnecessary end-of-message terminator to the xstat message.
![image](https://github.com/user-attachments/assets/5910b1eb-26b8-4ae5-a92b-8ce238e682b0)

This extra CRLF can be found on line 333 of rpt_manager.c
![image](https://github.com/user-attachments/assets/d2446c53-dcef-4cd3-84a4-e39a2e9f7e0b)

**Comment by W6HBR** [comment]
From some searching, it looks like the ctime() function adds the CRLF to the returned value.  If that is the case, then the extra CRLF on lines 27 & 28 should be removed.
![image](https://github.com/user-attachments/assets/d88a2d75-cd12-4a4a-ae81-d78a59044713)

**Comment by Allan-N** [comment]
Do you have any code / scripts that could be used to show (reproduce) the output?

**Comment by Allan-N** [comment]
And, yes, the ctime() strings ends in '\n'.  Easy enough to fix.

**Comment by W6HBR** [comment]
I can capture the raw AMI traffic if that is what you're asking for.  That's how I was able to figure out where the output was incorrect.

**Comment by Allan-N** [comment]
I was looking for some code, command, or script that I could run to see the output before making a change and confirming the expected/improved output afterwards.  Think "test code" :-)

**Comment by W6HBR** [comment]
To my knowledge, the only way to see the AMI traffic is to authenticate to an AMI session and capture it.  If you don't have a utility to do so, I can send you one I created for just this purpose.  You can then copy the output to Notepad++ or other editor where you can see the embedded\hidden CRLF characters.

![image](https://github.com/user-attachments/assets/b8809035-9355-4d5a-a34e-8be4efe34c8d)

![image](https://github.com/user-attachments/assets/650cb40e-65eb-4254-8c35-7fade497dd73)

**Comment by Allan-N** [comment]
The fix for this issue has been incorporated into ASL3-Asterisk 20.9.3+asl3-3.0.5-1
