### ISSUE TITLE
Repo includes (and builds) "pi-tune-menu"

### ISSUE THREAD

**Issue by Allan-N** [AllStarLink/app_rpt#414]
In the "utils" directory we have the SimpleUSB and USBRadio tune menus.  But, there is also a "pi-tune-menu" that we are still building and installing?  Seems like this should be removed (or at least no longer be built).  Or, if this menu is still valid then where does it fit in?

**Comment by KB4MDD** [comment]
chan_pi was not ported to asl3.  I don't see a need to include this with ASL3.

@tsawyer - do you know of anyone producing a pi hat that would need the chan_pi driver or the associated pi-tune-menu?
