### ISSUE TITLE
app_rpt: send_newkey, lock a channel that no longer exists 

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/app_rpt#85]
This core occurred when there was no console login or activity.

[core-asterisk-2023-02-04T23-52-39Z-brief.txt](https://github.com/InterLinked1/app_rpt/files/10609989/core-asterisk-2023-02-04T23-52-39Z-brief.txt)

**Comment by jxmx** [comment]
This does not seem to be any actionable issue. Closing to clean up GitHub. Reopen if there is a fixable problem.
